# -----------------------------
# アプリケーション名（任意）
# -----------------------------
spring.application.name=budget-app

# -----------------------------
# データベース接続設定（必須）
# -----------------------------
spring.datasource.url=jdbc:postgresql://localhost:5432/budget_app
spring.datasource.username=postgres
spring.datasource.password=TMGE1991
spring.datasource.driver-class-name=org.postgresql.Driver

# -----------------------------
# MyBatis設定
# -----------------------------
mybatis.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.mapper-locations=classpath*:mapper/**/*.xml
